bgcolor=292c3c # mantle
loginbox=292c3c # mantle

timecolor=c6d0f5 # text
greetercolor=c6d0f5 # text
layoutcolor=c6d0f5 # text

bshlcolor=e78284 # red

ringcolor=414559 # surface0
insidecolor=303446 # base
keyhlcolor=ca9ee6 # mauve

ringvercolor=ef9f76 # peach
insidevercolor=303446 # base
verifcolor=ef9f76 # peach

ringwrongcolor=e78284 # red
insidewrongcolor=303446 # base
wrongcolor=e78284 # red
