bgcolor=e6e9ef # mantle
loginbox=e6e9ef # mantle

timecolor=4c4f69 # text
greetercolor=4c4f69 # text
layoutcolor=4c4f69 # text

bshlcolor=d20f39 # red

ringcolor=ccd0da # surface0
insidecolor=eff1f5 # base
keyhlcolor=8839ef # mauve

ringvercolor=fe640b # peach
insidevercolor=eff1f5 # base
verifcolor=fe640b # peach

ringwrongcolor=d20f39 # red
insidewrongcolor=eff1f5 # base
wrongcolor=d20f39 # red
