bgcolor=1e2030 # mantle
loginbox=1e2030 # mantle

timecolor=cad3f5 # text
greetercolor=cad3f5 # text
layoutcolor=cad3f5 # text

bshlcolor=ed8796 # red

ringcolor=363a4f # surface0
insidecolor=24273a # base
keyhlcolor=c6a0f6 # mauve

ringvercolor=f5a97f # peach
insidevercolor=24273a # base
verifcolor=f5a97f # peach

ringwrongcolor=ed8796 # red
insidewrongcolor=24273a # base
wrongcolor=ed8796 # red
