bgcolor=181825 # mantle
loginbox=181825 # mantle

timecolor=cdd6f4 # text
greetercolor=cdd6f4 # text
layoutcolor=cdd6f4 # text

bshlcolor=f38ba8 # red

ringcolor=313244 # surface0
insidecolor=1e1e2e # base
keyhlcolor=cba6f7 # mauve

ringvercolor=fab387 # peach
insidevercolor=1e1e2e # base
verifcolor=fab387 # peach

ringwrongcolor=f38ba8 # red
insidewrongcolor=1e1e2e # base
wrongcolor=f38ba8 # red
